<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Simulation.Application\Simulation.Application.csproj" />
    <ProjectReference Include="..\Simulation.Domain\Simulation.Domain.csproj" />
  </ItemGroup>
</Project>